[package]
name = "primitive_operators"
version = "0.1.0"
edition = "2024"

[features]
macros = []

[dependencies]
arbitrary = { version = "1.4.2", features = ["derive"] }
strum = "0.28.0"
strum_macros = "0.28.0"
primitive_operators_macros = { path = "primitive_operators_macros" }

[dev-dependencies]
rand = "0.10.3"
