[package]
name = "primitive_operators"
author = "Ashraf Ibrahim"
version = "0.1.0"
edition = "2024"
license = "GPLv3"
keywords = ["arbitrary", "fuzzing", "operators"]
description = "Operators for constraining arbitrary types."
repository = "https://github.com/AshrafIbrahim03/primitive-operators"

[features]
macros = []

[dependencies]
arbitrary = { version = "1.4.2", features = ["derive"] }
strum = "0.28.0"
strum_macros = "0.28.0"
primitive_operators_macros = { version = "0.1.0", path = "./primitive_operators_macros" }

[dev-dependencies]
rand = "0.10.3"
